image: tiangolo/docker-with-compose:latest
stages:
  - build
  - bandit
  - safety
  - mypy
  - test


variables:
  REGISTRY_NAME: git.chocodev.kz:4567
  CONTAINER_IMAGE_NAME: git.chocodev.kz:4567/chocofood/seed
  CONTAINER_CURRENT_IMAGE_NAME: $CONTAINER_IMAGE_NAME:$CI_COMMIT_REF_SLUG

.build: &build
  stage: build
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_NAME
    - docker build -t $CONTAINER_CURRENT_IMAGE_NAME .
    - docker push $CONTAINER_CURRENT_IMAGE_NAME

.test: &test
  stage: test
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_NAME
    - cd CI/pipelines && docker-compose -f $FILE down && docker-compose -f $FILE pull
    - docker-compose -f $FILE up --abort-on-container-exit --remove-orphans && docker-compose -f $FILE down

build:
  <<: *build

test:
  variables:
    FILE: test.yml
  <<: *test

bandit:
  variables:
    FILE: bandit.yml
  <<: *test

safety:
  variables:
    FILE: safety.yml
  <<: *test
