image: docker-proxy.choco.kz/docker:20.10.0
stages:
  - build
  - test


variables:
  CONTAINER_CURRENT_IMAGE_NAME: docker-registry.choco.kz/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG

.build: &build
  stage: build
  tags:
    - docker
  script:
    - mkdir -p ~/.docker && echo ${NEXUS_REGISTRY} | base64 -d > ~/.docker/config.json
    - docker build -t $CONTAINER_CURRENT_IMAGE_NAME .
    - docker push $CONTAINER_CURRENT_IMAGE_NAME

build:
  <<: *build

lint:
  stage: test
  tags:
    - docker
  retry: 2
  image: ${CONTAINER_CURRENT_IMAGE_NAME}
  variables:
    PROCESS: LINT
  script:
    - cp ci_cd/ci/ci.env /src/core/.env && cd src && bash entrypoint.sh

test:
  stage: test
  tags:
    - docker
  retry: 2
  image: ${CONTAINER_CURRENT_IMAGE_NAME}
  variables:
    PROCESS: TEST
  script:
    - cp ci_cd/ci/ci.env /src/core/.env && cd src && bash entrypoint.sh
