version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    logging:
      driver: none
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.3-alpine
    logging:
      driver: none
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass

  django:
    container_name: django
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      MODE: DEV
      test: "pytest -v --cov . --cov-report term-missing
      --cov-fail-under=100 --flake8 -n 8 --no-migrations
      --reuse-db -W error"
      makemigrations: python manage.py makemigrations
      migrate: python manage.py migrate
      makemessages: python manage.py makemessages
      compilemessages: python manage.py compilemessages
      outdated: pip list --outdated --format=columns
      bandit: bandit -r .
      safety: safety check
      mypy: mypy .
      check: python manage.py check --deploy
      shell: python manage.py shell_plus
      flake8: flake8 .
      createsuperuser: "python manage.py createsuperuser
      --username=1 --email=muslimbeibytuly@gmail.com"


  celery:
    container_name: celery
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
      - rabbitmq
    environment:
      MODE: CELERY
